[project]
name = "akio"
version = "0.0.5.dev0"
description = "An agentic AI for red team tasks."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "browser-use>=0.7.10",
    "chromadb>=0.5.23",
    "docker>=7.1.0",
    "fastapi[standard]>=0.116.1",
    "mcp[cli]>=1.9.2",
    "ollama>=0.5.1",
    "openai-harmony>=0.0.8",
    "openai-whisper>=20250625",
    "playwright>=1.52.0",
    "pydantic>=2.10.6",
    "rich>=13.9.4",
    "transformers>=4.57.1",
    "watchdog>=6.0.0",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Development Status :: 2 - Pre-Alpha",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Unix",
  "Operating System :: MacOS",
  "Topic :: Security",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
keywords = [
  "ai",
  "llm",
  "agent",
  "autonomous",
  "pentest",
  "redteam",
  "local",
  "rag",
  "mcp"
]
authors = [
  { name = "Fastiraz" }
]
maintainers = [
  { name = "Fastiraz" }
]

[project.scripts]
akio = "akio.__main__:main"

[project.urls]
homepage = "https://github.com/fastiraz/akio"
issues = "https://github.com/Fastiraz/akio/issues"
repository = "https://github.com/fastiraz/akio"
documentation = "https://fastiraz.github.io/grimoire/"

[build-system]
requires = ["uv_build >= 0.7.19, <0.9.0"]
build-backend = "uv_build"

[tool.uv_build]
package-dir = { "akio" = "src/akio" }
include = [
    "src/akio/**",
    "src/akio/**/*.py"
]

[tool.ruff]
line-length = 80
exclude = ["datasets"]

[tool.ruff.lint.per-file-ignores]
"src/akio/__main__.py" = ["E402"]

[tool.ruff.format]
# TODO: indent width = 2
indent-style = "space"
quote-style = "double"
