#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# TODO: rewrite.
# Fix generated by AI. Rewrite as soon as possible.


import json
import os
from .constants import ConstantConfig, Color


class _Settings:
  """
  Settings class that lazy-loads configuration from JSON file.

  This class implements a singleton pattern with lazy initialization,
  loading the configuration file only when first accessed.

  Attributes:
    _config: Dictionary containing the loaded configuration.
    _initialized: Boolean flag indicating if configuration has been loaded.
  """

  _config = None
  _initialized = False

  def _load_config(self) -> None:
    """
    Lazy-load the configuration file.

    Creates a default configuration file if it doesn't exist, then loads
    the configuration from the JSON file. Only executes once per instance.
    """
    if not self._initialized:
      if not os.path.exists(ConstantConfig.AKIO_CONFIG_FILE):
        print(f'{Color.DIM}Creating default configuration...{Color.RESET}')
        os.makedirs(ConstantConfig.AKIO_CONFIG_PATH, exist_ok=True)
        default_config = {
          'llm_provider_base_url': 'http://localhost:11434',
          'base_model': 'qwen3:8b',
          'embedding_model': 'qwen3-embedding:0.6b',
          'vision_model': 'llava:7b',
          'coding_model': 'qwen2.5-coder:14b',
          'browser_model': 'qwen3:8b',
          'baas_base_url': 'http://localhost:8090',
          'chroma_base_url': 'http://localhost:8000'
        }
        with open(
          file=ConstantConfig.AKIO_CONFIG_FILE,
          mode='w',
          encoding='utf-8'
        ) as f:
          json.dump(default_config, f, indent=2)

      with open(
          file=ConstantConfig.AKIO_CONFIG_FILE,
          mode='r',
          encoding='utf-8'
      ) as f:
        self._config = json.load(f)
      self._initialized = True

  @property
  def llm_provider_base_url(self) -> str:
    """
    Returns the LLM provider base URL.

    Returns:
      str: The base URL for the LLM provider as configured.
    """
    self._load_config()
    return self._config['llm_provider_base_url']

  @property
  def base_model(self) -> str:
    """
    Returns the base model name.

    Returns:
      str: The name of the base model as configured.
    """
    self._load_config()
    return self._config['base_model']

  @property
  def embedding_model(self) -> str:
    """
    Returns the embedding model name.

    Returns:
      str: The name of the embedding model as configured.
    """
    self._load_config()
    return self._config['embedding_model']

  @property
  def vision_model(self) -> str:
    """
    Returns the vision model name.

    Returns:
      str: The name of the vision model as configured.
    """
    self._load_config()
    return self._config['vision_model']

  @property
  def coding_model(self) -> str:
    """
    Returns the coding model name.

    Returns:
      str: The name of the coding model as configured.
    """
    self._load_config()
    return self._config['coding_model']

  @property
  def browser_model(self) -> str:
    """
    Returns the browser model name.

    Returns:
      str: The name of the browser model as configured.
    """
    self._load_config()
    return self._config['browser_model']

  @property
  def baas_base_url(self) -> str:
    """
    Returns the BaaS (Backend as a Service) base URL.

    Returns:
      str: The base URL for the BaaS service as configured.
    """
    self._load_config()
    return self._config['baas_base_url']

  @property
  def chroma_base_url(self) -> str:
    """
    Returns the Chroma database base URL.

    Returns:
      str: The base URL for the Chroma database as configured.
    """
    self._load_config()
    return self._config['chroma_base_url']


_settings_instance = _Settings()


class _SettingsDescriptor:
  """
  Descriptor class for accessing settings attributes.

  This descriptor provides a way to access settings through class-level
  attributes while delegating to the singleton _Settings instance.

  Attributes:
    attr_name (str): The name of the attribute to access on the _Settings instance.
  """

  def __init__(self, attr_name: str) -> None:
    """
    Initialize the descriptor with an attribute name.

    Args:
      attr_name (str): The name of the attribute to access.
    """
    self.attr_name = attr_name

  def __get__(self, obj: object, objtype: type = None) -> str:
    """
    Get the attribute value from the settings instance.

    Args:
      obj: The instance that the attribute is being accessed from.
      objtype: The type of the instance (optional).

    Returns:
      The value of the requested attribute from the settings instance.
    """
    return getattr(_settings_instance, self.attr_name)


class Settings:
  """
  Settings class that provides class-level access to configuration.

  This class uses descriptors to provide convenient class-level access to
  configuration values stored in the singleton _Settings instance.
  """

  llm_provider_base_url = _SettingsDescriptor('llm_provider_base_url')
  base_model = _SettingsDescriptor('base_model')
  embedding_model = _SettingsDescriptor('embedding_model')
  vision_model = _SettingsDescriptor('vision_model')
  coding_model = _SettingsDescriptor('coding_model')
  browser_model = _SettingsDescriptor('browser_model')
  baas_base_url = _SettingsDescriptor('baas_base_url')
  chroma_base_url = _SettingsDescriptor('chroma_base_url')
